"""adding tables

Revision ID: 19c722955aea
Revises: None
Create Date: 2012-11-25 15:03:14.285000

"""

# revision identifiers, used by Alembic.
revision = '19c722955aea'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('application_number', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patents')
    op.drop_table('inventors')
    ### end Alembic commands ###
