"""addedd class and inventor

Revision ID: b111ea8d507
Revises: 19c722955aea
Create Date: 2012-11-25 17:59:40.757000

"""

# revision identifiers, used by Alembic.
revision = 'b111ea8d507'
down_revision = '19c722955aea'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=30), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('international_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['classifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('non_patent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pub_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docNumber', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('us_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['classifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docNumber', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('us_fieldsofresearch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['us_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patent_inventor',
    sa.Column('patent_id', sa.Integer(), nullable=True),
    sa.Column('inventor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventor_id'], ['inventors.id'], ),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.drop_column(u'inventors', u'name')
    op.add_column(u'patents', sa.Column('docNumber', sa.String(length=15), nullable=True))
    op.drop_column(u'patents', u'number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'patents', sa.Column(u'number', mysql.VARCHAR(length=15), nullable=True))
    op.drop_column(u'patents', 'docNumber')
    op.add_column(u'inventors', sa.Column(u'name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_table('patent_inventor')
    op.drop_table('us_fieldsofresearch')
    op.drop_table('app_references')
    op.drop_table('us_classes')
    op.drop_table('pub_references')
    op.drop_table('non_patent')
    op.drop_table('international_classes')
    op.drop_table('classifications')
    op.drop_table('references')
    op.drop_table('persons')
    op.drop_table('entities')
    ### end Alembic commands ###
